title: Mohammad Hemmat
description: AI & Robotics | Generative Models | Cybersecurity
theme: minima
author:
  name: Mohammad Hemmat
  email: # optional
  links:
    - label: Telegram
      url: https://t.me/Astr0Mh
    - label: Telegram Channel
      url: https://t.me/TheThoughtsDirectory
    - label: LinkedIn
      url: https://www.linkedin.com/in/mohammad-hemmat-talab-840412321
